version: 2

jobs:
  build:
    docker:
      - image: circleci/node:14.18@sha256:6f6b36595d00d61545f502d191c459a52e8f3d55a3607f4e2e2dd8f15a01c9ad
    steps:
      - checkout
      - restore_cache:
          keys:
            - install-dep-cache-{{ checksum "pnpm-lock.yaml" }}
      - restore_cache:
          keys:
            - v-11.0.0-electron
      - run:
          command: npm i --prefix=$HOME/.local -g pnpm
      - run:
          command: pnpm install --frozen-lockfile
      - run:
          command: pnpm compile
      - save_cache:
          key: install-dep-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          command: node ./test/out/helpers/downloadElectron.js
      - save_cache:
          key: v-11.0.0-electron
          paths:
            - ~/.cache/electron

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - docs